<h1>Hello, Oops</h1>

<p>The form below is an example form. </p>
<p>It will be processed with the <a href="http://en.wikipedia.org/wiki/Post/Redirect/Get">Post/Redirect/Get</a> technique if valid.</p> 



<div>
	<a class="button" href="<?php echo $this->url(array('action' => 'example')) ?>">SHOW ME A SMARTY VIEW</a> 
</div>

<hr />

<?php if (count($this->form->getMessages()) > 0) : ?>

	<div class="error">
		<span style="float:right">
			<a id="hideError" href=""><img alt="X" src="../img/admin/close.png"></a>
		</span>
		<img src="../img/admin/error2.png">2 erreurs<br>
		<ol>
			<?php foreach ($this->form->getMessages() as $message) : ?>
				<?php foreach ($message as $key => $value) : ?>
					<li><?php echo $value ?></li>
				<?php endforeach; ?>
			<?php endforeach; ?>
		</ol>
	</div>
	
<?php else : ?>

	<?php if (!empty($this->category) && !empty($this->text) && !empty($this->email)) : ?>
	
		<div class="conf">
			<p>You have selected category : <strong><?php echo $this->category->getName() ?></strong></p>
			<p>You have entered text : <strong><?php echo $this->text ?></strong></p>
			<p>You have entered email : <strong><?php echo $this->email ?></strong></p>
		</div>
	
	<?php endif; ?>
	
<?php endif; ?>

<!-- Render the form HTML code -->
<?php echo $this->form ?>

<hr />

<p>
	<a class="button" href="<?php echo $this->url(array('action' => 'index')) ?>">RESET THE FORM</a>
</p>




