<div class="block products_block">
	<h4><a href="#" title=""><?php echo $this->translate('hello_world') ?></a></h4>
	<div class="block_content">
	
		<p><?php echo $this->translate('click_to_load_ajax') ?></p>
	
		<strong>First level categories</strong>
		<ul>
		<?php foreach ($this->categories as $category) : ?>
			<li><?php echo $category->getName() ?></li>
		<?php endforeach; ?>
		</ul>
		
		<strong>Items</strong>
		<ul>
		<?php foreach ($this->items as $item) : ?>
			<li><?php echo $item ?></li>
		<?php endforeach; ?>
		</ul>
		
	</div>
</div>